### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by hdtopku** [macrozheng/mall#406]
`cms_prefrence_area_product_relation`和`cms_prefrence_area`中的`prefrence`应该为`preference`

**Comment by hdtopku** [comment]
`pms_product_vertify_record`中的`vertify`应改为`verify`

**Comment by hdtopku** [comment]
`recommand`应改为`recommend`，前端也需要做更改

**Comment by shubending** [comment]
你和之前找中文错别字的那个小伙可以交个朋友了

**Comment by aaa7636602** [comment]
啥意思 ---- 回复的原邮件 ***@***.***>发送日期2021年06月25日 16:53 ***@***.***> ***@***.***>主题Re: [macrozheng/mall] 单词拼写错误 (#406)

你和之前找中文错别字的那个小伙可以交个朋友了



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/macrozheng/mall/issues/406#issuecomment-868334481",

"url": "https://github.com/macrozheng/mall/issues/406#issuecomment-868334481",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yn197** [comment]
hahaha
