### ISSUE TITLE
请问部署到服务器 服务器大概需要多少内存才够啊

### ISSUE THREAD

**Issue by MrDevitt** [macrozheng/mall#508]
我4G内存腾讯云的服务器用docker部署
docker容器里跑了redis mysql rabbitMQ之后elasticsearch老是随缘退出 内存长期占到2.5g以上 
关掉mysql 启动elasticsearch内存能到3.几
请问内存就是要占用很多还是我自己配置有问题呀

**Comment by 201811510309-hjg** [comment]
开集群吧，再买几台服务器

**Comment by aliyun11** [comment]
良心云， 服务器 2核4g8m，198元/3年
# 传送门：https://curl.qcloud.com/AfDope6j
另外隔壁云也有优惠：https://www.aliyun.com/minisite/goods?taskPkg=1111ydsrwb&pkgSid=5985&recordId=953164&userCode=wbqjs7bw
ps：老用户，重新注册qq就可以白嫖了

![image](https://user-images.githubusercontent.com/93562479/141441690-21167243-f098-42fa-95e0-683d47c953ec.png)

**Comment by aaa7636602** [comment]
良心云！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月12日(星期五) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [macrozheng/mall] 请问部署到服务器 服务器大概需要多少内存才够啊 (Issue #508)





 
良心云， 服务器 2核4g8m，198元/3年
 
传送门：https://curl.qcloud.com/AfDope6j
 
另外隔壁云也有优惠：https://www.aliyun.com/minisite/goods?taskPkg=1111ydsrwb&amp;pkgSid=5985&amp;recordId=953164&amp;userCode=wbqjs7bw
 ps：老用户，重新注册qq就可以白嫖了
 

 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by macrozheng** [comment]
光Elasticsearch就得占1G内存，每个应用服务都得占0.5G内存，建议8G内存以上。
