### ISSUE TITLE
刚刚开始学习本项目，单表的查询通过mbg生成，多表的查询怎么自动生成？

### ISSUE THREAD

**Issue by lk101** [macrozheng/mall#512]
我注意到，mbg项目中将所有表的基本单表查询和更新通过mybatis generator工具实现了自动生成

除此之外，我还发现在admin项目中，src/main/resources/dao目录下还有一些手写的SQL，这些SQL对应的Java Dao和Dto类也是通过自动化工具自动生成的吗？

如果是，自动化生成的相关配置是否在项目中有所体现？

谢谢！

**Comment by lk101** [comment]
在mybatis官网上并未找到相关的自动生成方法和配置，是否是使用了其他工具？

**Comment by aaa7636602** [comment]
多表支持吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 下午3:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [macrozheng/mall] 刚刚开始学习本项目，单表的查询通过mbg生成，多表的查询怎么自动生成？ (Issue #512)





 
在mybatis官网上并未找到相关的自动生成方法和配置，是否是使用了其他工具？
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by macrozheng** [comment]
不是通过工具生成的，多表和复杂sql需要手写，`src/main/resources/dao`目录下的都是自定义sql。

**Comment by zkchen** [comment]
来信已收到。

**Comment by 516717906** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yufeng007** [comment]
这是一封自动回复邮件。
 
你好，来信已收到。感谢你的来信，阅后会尽快回复。
